# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# On force l'utilisation du JDK 17 qui est déjà sur votre machine
org.gradle.java.home=C:\\Users\\Dell\\AppData\\Local\\Programs\\Microsoft\\jdk-17.0.14.7-hotspot
org.gradle.daemon=false

android.useAndroidX=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

newArchEnabled=true
hermesEnabled=true
edgeToEdgeEnabled=true
android.enableLibraryMerging=true

android.builtInKotlin=false
android.newDsl=false
